.travis.yml

Travis checks out a specific commit which breaks branch detection by
detaching HEAD. This is a workaround

chore(ci): use Travis deploy

---

cmd/build.go
cmd/enforce.go
pkg/enforcer/enforcer.go
pkg/metadata/metadata.go
pkg/policy/conventionalcommit/conventionalcommit.go

feat: adding command line flag for commit msg
This allows someone to use `conform enforce` for commit-msg git hooks.

Allowing conform to be used in commit-msg git hooks

---

internal/policy/commit/commit.go

fix: ensure the imperative check is against lowercase word

---

.conform.yaml
LICENSE_HEADER
internal/policy/license/license.go

feat: change the license header to a string

---

internal/policy/commit/commit.go
internal/policy/commit/commit_test.go

Fixes https://github.com/autonomy/conform/issues/117 
Signed-off-by: Don Bowman <db@donbowman.ca>

fix: check empty commit-msg prior to parsing

---

internal/policy/license/license.go

`continue` was just running one more iteration `for` loop, being
effectively no-op.
While I'm at it, added another return to make sure file license
is validated only once even if matches multiple suffixes.

fix: excludeSuffixes wasn't skipping any files

---

.bettercodehub.yml
.codebeatignore
.conform.yaml
.drone.yml
Dockerfile
Makefile
README.md
hack/golangci-lint.yaml
hack/test.sh
internal/policy/commit/commit.go
internal/policy/commit/commit_test.go
internal/policy/license/license.go

This allows to skip directories which shouldn't be checked (e.g.
`.git/`) or directories which aren't readable.
While I was at it, bumped Go version, golangci-lint, refactored tests to
avoid duplicated code and make linter happy.
Rearranged a bit `Dockerfile` to avoid `go mod download` when `go.mod`
is not changed.

feat: implement `skipPaths` option for 'license' policy

---

internal/enforcer/enforcer.go

feat: add support for github status checks

---

.drone.yml

This PR enables images to be pushed on a merge, regardless of branch.

chore: push images for all branches

---

.conform.yaml

This PR enables requireCommitBody, which requires that all commits contain a body.

chore: require a commit body

---

internal/enforcer/enforcer.go

This PR sets the `pass` var in the `enforcer` code to `false` if there are errors in the policies.  This allows the command to return exit code 0 on success and exit code 1 on policy failures.
Signed-off-by: Peter Ng <peter@joincivil.com>

fix: set pass to false if errors in policies

---

internal/policy/commit/commit.go

Getting an `index out of range` panic if conventional commits is true and imperative verb is true and the message is not in a conventional commit format.  
This PR checks to ensure we get all the expected groups when the header is parsed. If not, fail as the string should be in a valid conventional commit format before we can figure out the first word for the imperative mood check.

fix: checks conventional commit format in firstWord

---

README.md

This adds missing documentation on how to install and use conform.

docs: add installation guide to README

---

cmd/enforce.go
cmd/root.go

Cobra will print a stacktrace if you forcibly close the process from within a `cmd.Run` function.
Using `RunE` and returning errors will prevent this.
Cobra will print errors returned this way for you, so the `fmt.Println(err)` in `rootCmd` was redundant.
You may also want to do this in the `serve` command, but I did not touch it right now.

fix: Correctly return errors from command run function

---

README.md
internal/policy/commit/check_conventional_commit.go

The max length for the description in a conventional commit was hardcoded to 72 characters. This change makes it configurable.
When no value is provided in the yaml, a default of 72 is used to keep backwards compatibility.
Signed-off-by: Wouter Dullaert <wouter.dullaert@gmail.com>

feat(policy): Make Conventional commit description configurable

---

.pre-commit-config.yaml
.pre-commit-hooks.yaml

pre-commit.com is a hook framework for automatically configuring a
repository to incorporate specified hooks for all developers

feat: add compatibility with pre-commit.com

---

README.md

Since we have official support for pre-commit.com now, the README
indicates how to get this included in compatible projects.

docs: update README to include pre-commit compatibility

---

.conform.yaml
README.md
internal/policy/commit/check_body.go
internal/policy/commit/check_header_case.go
internal/policy/commit/check_header_last_character.go
internal/policy/commit/check_header_length.go
internal/policy/commit/commit.go

I came across this project and loved the overall idea and the imperative check, but I noticed that some other common guidelines (restrictions on the leading case and trailing punctuation of the header) were missing; this adds checks to enforce those. The desired case can be specified as either "upper" or "lower"; the punctuation check is implemented as a general check for disallowing the last character in the header to be from any given set of characters.

feat: add checks for header case and last character

---

.conform.yaml
README.md
internal/policy/commit/commit.go

This adds a `body` field for options related to the commit body.
BREAKING CHANGE: This moves `spec.requireCommitBody` to
`spec.body.required`.

feat: move body options to dedicated field

---

cmd/enforce.go
cmd/serve.go
internal/enforcer/enforcer.go
internal/policy/policy.go
internal/reporter/reporter.go

This changes the nomenclature of the interface for reporting policy
statuses.
BREAKING CHANGE: This renames the `--summary` flag to `--reporter`.

refactor: rename summarizer to reporter

---

.conform.yaml
README.md
go.mod
go.sum
internal/policy/commit/check_spelling.go
internal/policy/commit/commit.go

This adds the ability to spellcheck commits. It supports US, UK, and GB
locales.
Closes  #125.

feat: add spellcheck commit check

---

internal/policy/commit/check_conventional_commit.go
internal/policy/commit/commit_test.go

This allows for regular expressions to be used in the scope of a
conventional commit.

feat: support regex in conventional commit scope

---

Dockerfile
Makefile
go.mod
go.sum
internal/policy/license/license.go

This allows to use `.gitignore` syntax for license policy `skipPaths`
property.

feat: implement full gitignore-style pattern matching

---

internal/policy/commit/commit.go

Fixes a type in the field name for Jira keys.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>

fix: change "jiraKeys" to "keys"

---

cmd/enforce.go
cmd/root.go
cmd/serve.go
cmd/version.go
hack/golangci-lint.yaml
hack/test.sh
internal/enforcer/enforcer.go
internal/git/git.go
internal/policy/commit/check_body.go
internal/policy/commit/check_conventional_commit.go
internal/policy/commit/check_dco.go
internal/policy/commit/check_gpg_signature.go
internal/policy/commit/check_header_case.go
internal/policy/commit/check_header_last_character.go
internal/policy/commit/check_header_length.go
internal/policy/commit/check_imperative_verb.go
internal/policy/commit/check_jira.go
internal/policy/commit/check_jira_test.go
internal/policy/commit/check_number_of_commits.go
internal/policy/commit/check_spelling.go
internal/policy/commit/commit.go
internal/policy/commit/commit_test.go
internal/policy/license/license.go
internal/reporter/reporter.go

chore: bump golangci-lint and fix linting issues
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
Note:
Copied `linter.disable` array and `golangci-lint` version from `talos` repository.

chore: bump golangci-lint and fix linting issues

---

internal/policy/commit/check_jira.go
internal/policy/commit/check_jira_test.go

This change fixes an issue that would allow JIRA-0 to be a valid Jira issue key. Id within Jira always start at 1, and cannot be prefixed by a any amount of leading 0's.
Fixes #191

fix: disallow 0 as valid jira issue id

---

internal/policy/commit/check_jira.go

By default, JIra project key must be at least 2 characters long and contain only uppercase letters.
https://confluence.atlassian.com/adminjiraserver/editing-a-project-key-938847080.html 
Fixes #197 
Signed-off-by: Anton Isakov <anton.isakov@dowjones.com>

fix: change check_jira regexp

---

internal/policy/commit/check_conventional_commit.go
internal/policy/commit/commit_test.go

Conventional Commit standard allows for "!" immediately following type
and preceding scope to indicate a breaking change. Conform fails against
this commit style, so this change allows such commit messages to pass
policy check.
Signed-off-by: Joey Espinosa <jlouis.espinosa@gmail.com>

Add Conventional Commit breaking change support

---

.conform.yaml
README.md
cmd/conform/serve.go
go.mod
internal/enforcer/enforcer.go
internal/policy/commit/check_jira_test.go
internal/policy/commit/commit_test.go
internal/policy/license/license.go
internal/policy/license/license_test.go

Useful for controller-gen and other code generators.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>

feat: allow comments before the license header

---

internal/policy/commit/check_jira.go

Currently when the Jira issue check passes it responds with `Jira issues are invalid`. This updates the check to return the expected message.

fix: update jira issue valid message

---

cmd/conform/serve.go

This is the 2nd attempt to fix checkout with symlinks via go-git.
The first `clone` action was checking out `master` branch, and then
switching to the PR branch. This causes issues wigh `go-git`, and we
don't need to checkout `master` branch for real.

fix: checkout a branch only once

---

internal/policy/commit/check_conventional_commit.go
internal/policy/commit/commit_test.go

The `!` goes after the scope, not before.
This also updates the Conventional Commits version in comments.
This also standardizes some test/function names.
This is a followup to https://github.com/talos-systems/conform/pull/203.

fix: field order for breaking conventional commit

---

.conform.yaml
.drone.yml
cmd/conform/enforce.go
internal/git/git.go
internal/policy/commit/commit.go
internal/policy/commit/commit_test.go
internal/policy/license/license_test.go
internal/policy/license/testdata/data.txt
internal/policy/policy_options.go

This is a proposal that enables enforcing policies on a range of commits, which is handy in CIs when a pull request contains multiple commits.
---
Add the ability to enforce commit policies on a commit range.
Two options are available:
- --revision-range <commit1..commit2>: analyse the given git revision
range
- --base-branch <name>: convenience for --revision-range name..HEAD
If commit1 is not an ancestor of commit2, the merge base (first common
ancestor) is used as first commit.
Signed-off-by: Vincent Dupont <vincentdup@gmail.com>

feat: add multi commit support

---

action.yml

This bumps the action image to latest 0.1.26.
It also adds the needed enforce arg.
Signed-off-by: Josef Andersson <josef.andersson@gmail.com>

fix: bump action image v0.1.0-alpha.26-3-g6380738

---

internal/policy/commit/check_conventional_commit.go

In semantic versioning, a feature leads to a minor release and a fix leads to a patch release. This was stated incorrectly in comments defining the corresponding types for feat and fix.

docs: correct comments about feat/fix

---

internal/enforcer/enforcer.go
internal/policy/license/license.go
internal/policy/license/license_test.go
internal/policy/license/testdata/subdir1/data.txt
internal/policy/license/testdata/subdir1/subdir2/data.txt

feat: add support for multiple licenses
Allow specifying multiple policy documents of `type: commit` in `.conform.yaml`.
Join these multiple policy declarations into a single license check policy.
In the license check spec, introduce a new field, `root`, to allow specifying in which directory that license check should run.
With this change, a single repository will be able to have different license rules for different paths.
Sample conform file with the changes:
```yaml
policies:
- type: commit
spec: "..."
- type: license
spec:
includeSuffixes:
- .go
excludeSuffixes:
- .pb.go
- .pb.gw.go
header: "// ROOT LICENSE"
- type: license
spec:
root: staging/client/
includeSuffixes:
- .go
excludeSuffixes:
- .pb.go
- .pb.gw.go
header: "// SUBDIR LICENSE"
```

feat: add support for multiple licenses

---

README.md

Example code to run in a container didn't work on SELinux systems.
Added filesystem labeling flag to the volume bind mount.
Change will not affect non-SELinux systems.
Also added read-only flag, since conform doesn't need write access.

docs: fix container run option for selinux systems
