.conform.yaml
pkg/renderer/renderer.go

feat(renderer): allow templates to be retrieved from URL

---

.conform.yaml
.travis.yml
Gopkg.lock
cmd/enforce.go
pkg/metadata/metadata.go

feat(metadata): allow users to specify variables

---

README.md

fix: use mood instead of verb

---

CHANGELOG.md

chore: prepare v0.1.0-alpha.10 release

---

Makefile

chore: quote docker creds

---

internal/policy/commit/commit.go
internal/policy/commit/commit_test.go

fix: trim whitespace while validating DCO

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.12

---

.drone.yml
internal/enforcer/enforcer.go
internal/git/git.go
internal/summarizer/summarizer.go

feat: add support for GH actions on forked repo PRs

---

CHANGELOG.md

chore: prepare release v0.1.0-alpha.14

---

.drone.yml
Makefile

chore: build image with host net to avoid apk hang

---

.conform.yaml
internal/git/git.go
internal/policy/commit/check_number_of_commits.go
internal/policy/commit/commit.go

feat: add number of commits check

---

internal/policy/commit/check_body.go
internal/policy/commit/commit.go

feat: add commit body check

---

Dockerfile

This addresses issues faced when trying to publish conform as a GitHub action.

chore: fix container labels

---

internal/policy/commit/check_body.go
internal/policy/commit/check_number_of_commits.go

This PR adds in conditionals to send the proper message in the case of an error.

fix: print an error message

---

.drone.yml
Dockerfile
action.yml
cmd/serve.go
internal/summarizer/summarizer.go

This file is required in order to publish to the marketplace.

fix: add action.yml

---

cmd/enforce.go
cmd/serve.go
internal/policy/commit/commit.go
internal/policy/policy_options.go

This ensures that we checkout pull requests in server mode.

fix: checkout pull requests

---

cmd/root.go
cmd/version.go
hack/golangci-lint.yaml
hack/test.sh
internal/constants/constants.go
internal/enforcer/enforcer.go
internal/git/git.go
internal/policy/commit/check_body.go
internal/policy/commit/check_conventional_commit.go
internal/policy/commit/check_dco.go
internal/policy/commit/check_gpg_signature.go
internal/policy/commit/check_header_case.go
internal/policy/commit/check_header_last_character.go
internal/policy/commit/check_imperative_verb.go
internal/policy/commit/check_number_of_commits.go
internal/policy/commit/commit.go
internal/policy/commit/commit_test.go
internal/policy/license/license.go
internal/policy/policy.go
internal/policy/version/version.go
internal/reporter/reporter.go

chore: bump golangci-lint and fix linting issues

---

.drone.yml
Dockerfile
Makefile

We not longer use this tool.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>

chore: remove gitmeta

---

internal/policy/commit/check_jira.go
internal/policy/commit/check_jira_test.go
internal/policy/commit/commit.go

Fixes a few minor issues:
- make square brackets optional
- allow for conventional commit scopes to be present
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>
cc @olivernybroe @andrevalentin @flyhard

feat: improve Jira check

---

action.yml

Bumps the version of `conform` in `action.yml`.
Signed-off-by: Andrew Rynhard <andrew@rynhard.io>

fix: update action version

---

README.md

Update sample config and examples, install instructions.

docs: update README with the latest changes

---

CHANGELOG.md

This is the official v0.1.0-alpha.23 release.
Signed-off-by: Alexey Palazhchenko <alexey.palazhchenko@talos-systems.com>

release(v0.1.0-alpha.23): prepare release

---

CHANGELOG.md

This is the official v0.1.0-alpha.24 release.

release(v0.1.0-alpha.24): prepare release

---

CHANGELOG.md

This is the official v0.1.0-alpha.25 release.

release(v0.1.0-alpha.25): prepare release

---

.conform.yaml
.golangci-lint.yaml
.pre-commit-config.yaml
Dockerfile
Makefile
README.md
hack/release.sh
hack/release.toml

Rename org
Signed-off-by: Noel Georgi <git@frezbo.dev>

chore: rename org

---

CHANGELOG.md

This is the official v0.1.0-alpha.26 release.
Fixes #223 

release(v0.1.0-alpha.26): prepare release

---

.github/workflows/ci.yaml
.golangci.yml
.kres.yaml
Dockerfile
Makefile
hack/release.sh
internal/enforcer/enforcer.go
internal/policy/commit/check_gpg_identity.go
internal/policy/commit/check_jira_test.go
internal/policy/commit/commit_test.go

chore: enable arm64 conform image

---

.pre-commit-config.yaml
README.md

Changes the branch used by pre-commit from master to main

docs: update the pre-commit repo branch
